title: "Bayesian Stats and Probabilistic Programming"
email: "kentaaratani@coinez.jp"
description: "A reflection through my journey of Bayesian statistics and probabilistic programming."
baseurl: "" # Leave this empty if your site is at the root
url: "https://username.github.io" # Base URL of your site
theme: minima
markdown: kramdown

# Permalink configuration for pages
permalink: /:title/

usemathjax: true
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax