title: "Bayesian Stats and Probabilistic Programming"
email: "your-email@example.com"
description: "A journey through Bayesian statistics and probabilistic programming."
baseurl: "" # Leave this empty if your site is at the root
url: "https://username.github.io" # Base URL of your site
theme: minima
markdown: kramdown

# Permalink configuration for pages
permalink: /:title/