title: From Bayesian Statistics to Probabilistic Programming
email: kentaaratani@coinez.jp
description: >- # this means to ignore newlines until "baseurl:"
  An introductory piece for the curious that aims to take a look at both
  Bayesian Statistics and Probabilistic Programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coinez-jpn.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed